contentful/contentful-migration

- README.md
- docs/validation.md
- Link to Contentful CLI.
- Formatting of documentation parameters.
> fix(readme): Formatting and link fixes

- lib/migration-payloads/validation/schema-validation.js
- test/unit/lib/migration-payloads/validation/payload-validation.spec.js
Fixes https://github.com/contentful/migration-cli/issues/2
> fix(validation): allow "Location" field type

- docs/validation.md
Following up on my change request in #11
> Add missing validations for field scope

- bin/contentful-migration.js
Previously, syntax errors in the user's migration script were reported as the file not having been found.
> fix: Do not report syntax errors as "file not found"

- lib/migration-payloads/validation/field-validations.js
- test/unit/lib/migration-payloads/validation/payload-validation-field-validations.spec.js
> Allow custom field validation error messages

- src/lib/action/entry-field-rename.ts
- src/lib/action/field-rename.ts
- src/lib/intent/base-intent.ts
- src/lib/intent/field-rename.ts
- src/lib/migration-chunks/validation/content-type.ts
- src/lib/package/index.ts
- test/unit/lib/intent/field-rename.spec.ts
Refactoring to remove separate code path for field renaming, all self contained intents now 👍
> Reflect field rename on entries

- src/bin/lib/plan-messages.ts
Avoid polyfilling `Object.values
> wip: use lodash.values instead of Object.values

- examples/13-payload-validations.js
- test/end-to-end/assertions.js
- test/end-to-end/payload.spec.js
And now added payload validations e2e tests
> test(e2e): payload validations tests

- src/bin/cli.ts
Fixes https://github.com/contentful/migration-cli/issues/62
> fix: interpret yes flag as boolean

- README.md
- bin/contentful-migration
- package-lock.json
- src/bin/cli.ts
- src/bin/usage-params.ts
> WIP feat: Improve usage as a lib

- CONTRIBUTING.md
Came around this issue when setting this project up on my machine
> docs(README): add integration test space name hint

- examples/18-change-editor-interface-for-existing-content-type-adding-help-text.js
- src/lib/action/editorinterface-update.ts
- src/lib/entities/content-type.ts
- src/lib/intent/editorinterface-update.ts
- src/lib/interfaces/content-type.ts
- src/lib/interfaces/raw-step.ts
- src/lib/migration-steps/action-creators.ts
- src/lib/migration-steps/index.ts
- test/integration/migration.spec.js
- test/unit/lib/migration-steps/migration-steps.spec.js
> Add Editor Interfaces Settings

- src/bin/cli.ts
Fixes https://github.com/contentful/contentful-migration/issues/93
> fix: set environment default to master

- src/bin/cli.ts
- src/bin/lib/config.ts
- src/bin/lib/render-migration.ts
This PR defaults the environment to master
Closes https://github.com/contentful/contentful-migration/issues/117
> fix: default env to master

- README.md
Fix unterminated code block in README
The code block related to the proxy at the end of the README isn't terminated so encompasses all the subsequent headings, text etc
Self explanatory 
-   [x] Make a cup of tea
-   [ ] Get pull request accepted
N/A
> Fix unterminated code block in README

- README.md
- index.d.ts
- src/lib/offline-api/validator/schema/fields-schema.ts
- test/end-to-end/assertions.js
- test/unit/lib/offline-api/validation/payload-validation.spec.ts
> feat(Field): Add Rich text to field schema

- README.md
So me again, @TimBeyer 
this is the new pull request for the extended readme file.
Cheers,
Gordon
> readme extended with action transformEntriesToType

- index.d.ts
- src/bin/lib/config.ts
- src/bin/lib/contentful-client/index.ts
- src/bin/lib/contentful-client/proxy.ts
- test/unit/bin/lib/config.spec.ts
Allows `proxy` and `rawProxy` in argv.
> Allow proxy options in argv

- src/lib/offline-api/index.ts
> fix: Safer reads on entry fields properties inside getLinks() method for Offline API

- src/bin/cli.ts
Fixes https://github.com/contentful/contentful-migration/issues/189
> fix(migration): Remove path join

- README.md
The readme file shows parameters in wrong order
Updated the order of the parameters send to `changeFieldControl()`
> Updated order of parameters in changeFieldControl

- README.md
README Code block syntax highlighting fixes
README Code block syntax highlighting fixes
> fix bash code-block type and add others

- README.md
Reverts contentful/contentful-migration#195
> Revert "Updated order of parameters in changeFieldControl"

- README.md
Reverts contentful/contentful-migration#199
> Revert "Revert "Updated order of parameters in changeFieldControl""

- README.md
> Spelling correction: tranform to transform

- src/lib/offline-api/validator/schema/field-validations-schema.ts
This PR fixes unwarranted validation errors by updating the date range validation schema.
> Address dateRange validation error

- README.md
> perf(release): Prepare for v1 release

- README.md
> fix(docs): Update shouldPublish options

- package-lock.json
- package.json
- test/end-to-end/flags.spec.js
* update yargs and update some tests running the help cmd
* update semantic release
> fix(deps): update dependencies to fix vulnerabilities

- README.md
Since `makeRequest` function uses `await` keyword, it should be `async`.
> docs(README): mark usages of makeRequest as async

- README.md
- index.d.ts
This is supposed to be a fix for #241.
> fix(types): Update typechecks for ITransformEntriesToTypeConfig

- README.md
The documentation states the wrong defaults for the `shouldPublish` property.
-   [x] Feature with pending implementation
> fix(documentation): Make documentation reflect the current behaviour

- package-lock.json
- package.json
Windows users experienced "frozen" terminals after use input. A newer version of Inquirer resolved the problem in my test case.
> fix(deps): Older inquirer lib had a bug in Windows

- src/lib/migration-chunks/validation/errors.ts
- test/unit/lib/migration-chunks/validation/field/delete.spec.js
Fixes https://github.com/contentful/contentful-cli/issues/94#issuecomment-582357151
> Make CONTENT_TYPE_DOES_NOT_EXIST error more specific.

- package-lock.json
- src/bin/cli.ts
Resolves #249 
This PR introduces a change that allows for type errors to be processed similar to regular request errors as against erroring out in a way that seems like contentful migration is broken.
> Batch report type errors

- .dependabot/config.yml
- package.json
Enable dependabot and set it to merge automaticallu
> chore: add and configure dependabot

- .circleci/config.yml
- package-lock.json
- package.json
Copy + Paste gone wrong
Also enables the github release plugin for semantic-release.
> chore: use correct test step names and enable github release

- README.md
- index.d.ts
- package.json
- src/index.ts
Adds an src/index.ts file exporting the cli's runMigration
function. Fixes eslint/no-unresolved linter errors in 
dependent projects and makes using the cli as a library easier.
> fix: add index.ts and make package.json refer to it in main field

- test/end-to-end/content-transform.spec.js
- test/end-to-end/derive-entry.spec.js
- test/fixtures/contentful-migration-integration.js
- test/integration/migration.spec.js
- Adjust e2e and integration tests + provide updated nock templates
> Adjust e2e tests so that they work with a test space that has tags enabled

- README.md
- src/bin/lib/config.ts
- src/bin/usage-params.ts
- src/lib/fetcher.ts
- src/lib/migration-parser.ts
- test/integration/migration.spec.js
- test/unit/bin/lib/config.spec.ts
- test/unit/lib/content-types-in-chunks.spec.ts
- test/unit/lib/fetcher.spec.ts
- test/unit/lib/migration-parser.spec.ts
In some cases, the default request limit of 100 is not sufficient. 
This PR exposes a configurable limit parameter.
A new parameter `requestBatchSIze` can be set on cli or config file (contentfulrc.json) level.
> feat(cli): configurable per request limit

- package-lock.json
- package.json
Ease generation of correct commit msgs.
> chore: add commitizen to ease semver commits

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
- src/bin/cli.ts
- src/bin/lib/contentful-client/index.ts
- src/lib/fetcher.ts
- test/integration/bin/lib/contentful-client.spec.js
- test/integration/setup.js
Updating to new major version of CMA SDK and using the plain client. This causes a breaking change in case users consume the `createManagementClient` function.
@ruderngespra is there anything left in regards to documentation inside this repo?
> Use cma plain client

- .circleci/config.yml
Integrating Coverity SAST scan to the pipeline, to scan for security issues in the code.
> [SEC-1561] chore: add coverity scan to the pipeline

- examples/15-derive-entry-n-to-1.js
> Correct Comment

- src/lib/fetcher.ts
- src/lib/intent/base-intent.ts
- src/lib/intent/composed-intent.ts
- src/lib/intent/entry-derive.ts
- src/lib/intent/entry-set-tags.ts
- src/lib/intent/entry-transform-to-type.ts
- src/lib/intent/entry-transform.ts
- src/lib/intent/tag-create.ts
- src/lib/intent/tag-delete.ts
- src/lib/intent/tag-update.ts
- src/lib/interfaces/intent.ts
- src/lib/offline-api/index.ts
- test/end-to-end/content-transform.spec.js
- test/fixtures/contentful-migration-integration.js
- test/unit/lib/actions/entry-transform.spec.ts
- test/unit/lib/fetcher.spec.ts
- test/unit/lib/migration-parser.spec.ts
we'll fetch tags when the intent is content transform 
This PR will fix https://github.com/contentful/contentful-migration/issues/610
> fix(tags): fetch tags in entry-transform [1600]

- src/lib/action/entry-derive.ts
- src/lib/intent-validator/entry-derive.ts
- test/unit/lib/actions/entry-derive.spec.js
- test/unit/lib/intent-validator/entry-derive.spec.ts
Fix typescript error on EntryDeriveValidator found here: [pull/735](https://github.com/contentful/contentful-migration/pull/735)
> fix(entry-derive-validator): fix joi TS error

- README.md
- index.d.ts
Add `trackingFieldId` setting description to the README.
> docs: document trackingFieldId setting

- index.d.ts
adjust type according implementation
solves #709
> fix(types): addSidebarWidget

- index.d.ts
reflect internal changes in public declaration file
solves #887 
> fix/types): extend widget namespace type

- examples/33-create-fields-with-default-values.js
- test/integration/migration.spec.js
run default value example as part of integration tests.
> chore(tests): default value integration test

- .eslintrc.js
- examples/19-bad-validations.js
- examples/31-set-tags-for-entries.js
- package-lock.json
- package.json
- src/bin/lib/config.ts
- test/end-to-end/content-transform.spec.js
- test/end-to-end/derive-entry.spec.js
- test/end-to-end/sidebar.spec.js
- test/integration/bin/lib/contentful-client.spec.js
- test/integration/migration.spec.js
- test/unit/bin/lib/config.spec.ts
- test/unit/lib/entities/entry.spec.js
- test/unit/lib/migration-chunks/validation/content-type.spec.js
- test/unit/lib/migration-chunks/validation/field/change-id.spec.js
- test/unit/lib/migration-chunks/validation/field/create.spec.js
- test/unit/lib/migration-chunks/validation/field/delete.spec.js
- test/unit/lib/migration-chunks/validation/field/edit.spec.js
- test/unit/lib/migration-chunks/validation/field/move.spec.js
- test/unit/lib/migration-chunks/validation/tag.spec.js
- test/unit/lib/migration-steps/migration-steps.spec.js
- test/unit/lib/step-validator/field-movement.spec.js
- test/unit/lib/step-validator/updates.spec.js
Add standard header to requests
Fix various linting issues
> feat(config): Add standard header

- examples/xx-create-editor-layout.js
- examples/xx-delete-editor-layout-field-set.js
- examples/xx-delete-editor-layout-tab.js
- src/lib/action/editor-layout/editor-layout-delete-field-group.ts
- src/lib/entities/content-type.ts
- src/lib/intent/base-intent.ts
- src/lib/intent/composed-intent.ts
- src/lib/intent/editor-layout/editor-layout-create-field-group.ts
- src/lib/intent/editor-layout/editor-layout-delete-field-group.ts
- src/lib/interfaces/intent.ts
- src/lib/migration-chunks/validation/editor-layout.ts
- src/lib/migration-chunks/validation/errors.ts
- src/lib/migration-chunks/validation/index.ts
- src/lib/migration-parser.ts
- src/lib/utils/editor-layout.ts
- test/integration/migration.spec.js
- test/unit/lib/entities/editor-interface.spec.ts
- test/unit/lib/migration-chunks/validation/editor-layout.spec.js
- test/unit/lib/migration-chunks/validation/validate-chunks.ts
* Implement field group deletion (interface was already there)
* Add validation for existing / duplicate field group IDs
* Add validation for deleting unknown field group / deleting field group twice
-   [x] Add example / integration test for field group deletion
-   [x] Add unit test for validations
> Editor layout validation (first round) [DANTE-157]

- docs/validation.md
- src/lib/intent-list/index.ts
- src/lib/intent/composed-intent.ts
- src/lib/intent/editor-layout/editor-layout-change-field-group-control.ts
- src/lib/intent/editor-layout/editor-layout-delete-field-group.ts
- src/lib/intent/editor-layout/editor-layout-move-field.ts
- src/lib/intent/editor-layout/editor-layout-update-field-group.ts
- src/lib/offline-api/index.ts
- src/lib/offline-api/validator/editor-interface.ts
- src/lib/offline-api/validator/errors.ts
- src/lib/offline-api/validator/schema/editor-layout-schema.ts
- src/lib/offline-api/validator/schema/schema-validation.ts
- test/unit/lib/migration-chunks/validation/editor-layout.spec.js
- test/unit/lib/offline-api/validation/validate-batches.ts
Add a schema and a validator for the editor interface as a whole. Cover the first validation error (more than 2 levels of nesting).
> feat: validate editor layout [DANTE-407]

- examples/xx-change-field-group-id-editor-layout.js
- examples/xx-delete-editor-layout.js
- index.d.ts
- src/lib/action/editor-layout/editor-layout-delete.ts
- src/lib/action/editor-layout/editor-layout-update-field-group.ts
- src/lib/entities/content-type.ts
- src/lib/intent/editor-layout/editor-layout-change-field-group-id.ts
- src/lib/intent/editor-layout/editor-layout-delete.ts
- src/lib/intent/index.ts
- src/lib/interfaces/raw-step.ts
- src/lib/migration-chunks/validation/editor-layout.ts
- src/lib/migration-chunks/validation/errors.ts
- src/lib/migration-steps/action-creators.ts
- src/lib/migration-steps/index.ts
- test/integration/migration.spec.js
- test/unit/lib/migration-chunks/validation/editor-layout.spec.js
Functions to change field group id and delete editor layout
> feat: change field group id and delete editor layout

- README.md
The function description says that the `id` parameter will be used to identify the field to be deleted.
This change will fix and improve the documentation.
> Fix README.md in the editField section

- index.d.ts
#1028 added a new `retryLimit` parameter, this PR updates the corresponding type
> fix: add retryLimit to RunMigrationConfig type

- package-lock.json
- package.json
- src/lib/offline-api/validator/schema/schema-validation.ts
> chore: switch hoek packages [NONE]

- .circleci/config.yml
- .contentful/vault-secrets.yaml
- .github/workflows/dependabot-approve-and-request-merge.yml
Update the repo to use vault secrets
Changes dependabot from using a static secret to using the vault
-   [x] Add VAULT_URL to secrets
> feat: use vault secrets

- .contentful/vault-secrets.yaml
Update vault policies to use vault secrets for releasing
Part of updating all repos to use the vault
> feat: add  to vault policies [SDK-2259]

- .circleci/config.yml
- .contentful/vault-secrets.yaml
Change secrets from CircleCI context to vault
> feat: use vault to get secrets for releasing [SDK-2259]

- README.md
- docs/validation.md
- examples/47-create-resource-link-fields.js
- index.d.ts
- src/lib/intent-validator/field-update.ts
- src/lib/interfaces/content-type.ts
- src/lib/offline-api/index.ts
- src/lib/offline-api/validator/errors.ts
- src/lib/offline-api/validator/resource-links.ts
- src/lib/offline-api/validator/schema/fields-schema.ts
- src/lib/offline-api/validator/schema/schema-validation.ts
- src/lib/utils/resource-links.ts
- test/end-to-end/assertions.js
- test/end-to-end/content-type.spec.js
- test/integration/migration.spec.js
- test/unit/lib/offline-api/validation/payload-validation-items.spec.ts
- test/unit/lib/offline-api/validation/payload-validation-resource-links.spec.ts
- test/unit/lib/offline-api/validation/payload-validation.spec.ts
Add support for resource links.
* Add _ResourceLink_ field type
* Add `allowedResources` field property
* Validate resource link and allowed resource count
* Validate `allowedResources` structure
> feat: add resource link support and validation

- src/lib/offline-api/validator/schema/field-validations-schema.ts
Feature announcement: [link](https://www.contentful.com/developers/changelog/#superscript-and-subscript-in-the-rich-text-editor)
> fix(schema): allow superscript/subscript RT marks

- .gitignore
- .mocharc.js
- package.json
- test/mocha.opts
- test/teardown.js
- switch to new mocha config file format
- add tooling to delete outdated test environments
> chore: improve test setup [NONE]

- examples/43-assign-field-annotations.js
- examples/44-clear-field-annotations.js
- src/lib/action/field-annotate.ts
- src/lib/entities/content-type.ts
- src/lib/intent/field-annotate.ts
- src/lib/interfaces/annotation.ts
- src/lib/interfaces/raw-step.ts
- src/lib/migration-steps/action-creators.ts
- src/lib/migration-steps/index.ts
- test/integration/migration.spec.js
After introducing GraphQL field annotations for delivery functions, we need to support that feature here too
> feat: support graphQL annotations [MONET-1302]

- package-lock.json
- package.json
upgrade the dependency on CMA.js
> fix: upgrade CMA dependency

- .circleci/config.yml
- package.json
> Master to main

- src/lib/offline-api/validator/schema/field-validations-schema.ts
Allow new mark strikethrough for rich text
> feat: allow strikethrough
