contentful/contentful-migration

examples/07-display-field.js

Because otherwise without it the example fails to run.

fix(examples): display field in example to an existing field

---

package.json
test/integration/setup.js
test/setup.js

Because it's annoying to provide those env values even when only running the unit tests.

chore(): don't require integration config in unit tests

---

docs/validation.md

Since we have errors with the same name applied to different types and actions we need to scope them to eliminate any possible ambiguity.

docs(): prefix error keys with the type and action

---

bin/lib/plan-messages.js
docs/validation.md
examples/08-move-field.js
lib/migration-chunks/validation/errors.js
lib/migration-chunks/validation/field.js
lib/migration-payloads/index.js
lib/migration-steps/action-creators.js
lib/migration-steps/errors.js
lib/migration-steps/index.js
lib/migration-steps/validation.js
test/unit/lib/migration-chunks/validation/field/move.spec.js
test/unit/lib/migration-payloads/payload-builder.spec.js
test/unit/lib/migration-steps/migration-steps-validation.spec.js

Extend the migration language with methods to move a field within a CT. Moving a field within a CT has impact in how the field of an entry of the edited content type are later displayed in Contentful Webapp (i.e. fields moved to top will be displayed on top when editing an entry and so on).
If fields are not reordered they will be displayed in the order they are added.
Plan output:
```bash
The following migration has been planned
Update Content Type food
Create field calories
- type: "Number"
- name: "How many calories does it have?"
Move field calories to the first position
Create field sugar
- type: "Number"
- name: "Amount of sugar"
Move field sugar to the last position
Create field vegan
- type: "Boolean"
- name: "Vegan friendly"
Create field producer
- type: "Symbol"
- name: "Food …
```

Field reordering

---

README.md
docs/validation.md
examples/change-field-id.js
lib/migration-chunks/index.js
lib/migration-chunks/slicers/field-id-change.js
lib/migration-chunks/validation/errors.js
lib/migration-chunks/validation/field.js
lib/migration-payloads/index.js
lib/migration-payloads/validation/errors.js
lib/migration-payloads/validation/schema-validation.js
lib/migration-steps/action-creators.js
lib/migration-steps/index.js
lib/migration-steps/validation.js
test/integration/migration.spec.js
test/unit/lib/migration-chunks/migration-chunks.spec.js
test/unit/lib/migration-chunks/validation/field/change-id.spec.js
test/unit/lib/migration-payloads/payload-builder.spec.js
test/unit/lib/migration-payloads/validation/payload-validation-id-change.spec.js
test/unit/lib/migration-payloads/validation/validate-payloads.js
test/unit/lib/migration-steps/migration-steps.spec.js

This adds a `.changeFieldId()` method to content types, allowing users to change a field's ID.
It validates and covers the cases mentioned in `validation.md`.

Change field id

---

lib/migration-chunks/validation/errors.js
lib/migration-chunks/validation/field.js
test/unit/lib/migration-chunks/validation/field/change-id.spec.js
test/unit/lib/migration-chunks/validation/field/edit.spec.js

When validating a field ID change, we should perform all the basic checks that are done on a field update as well (such as checking if the field exists at all). 
That's why the 'field/update' check error messages should be worded more generally ("edit field" instead of "set property on field") so they work for edits of all kinds.

fix(fields): Before id change, check if field exists

---

lib/migration-payloads/validation/errors.js
lib/migration-payloads/validation/schema-validation.js
test/unit/lib/migration-payloads/validation/payload-validation-field-validations.spec.js

As mentioned in #20, currently the validation message is not very meaningful when you have an additional un-allowed property in an otherwise valid validation object.

Show invalid combination of validation props

---

test/unit/lib/migration-payloads/validation/payload-validation-field-validations.spec.js

After #23 was merged before #22, `message` is now an allowed key and therefore isn't mentioned in `keys` array of `object.unknownCombination` error.

Test for invalid field validation used valid key

---

docs/validation.md
lib/migration-chunks/validation/duplicate-props.js
lib/migration-chunks/validation/errors.js
lib/migration-chunks/validation/index.js
test/unit/lib/migration-chunks/validation/content-type.spec.js
test/unit/lib/migration-chunks/validation/field/create.spec.js
test/unit/lib/migration-chunks/validation/field/edit.spec.js

Previously, users could set a property on the same entity multiple times. This got collapsed into the correct payload but was showing the duplicates when rendering the plan. 
This PR introduces duplicate props validation for chunks, meaning props cannot be set multiple times within the same chunk (but setting them several times in separate chunks is ok).
The validation is happening after content type and fields validation, because it needs to look at a chunk including all its steps and because it makes sense to perform those basic validations first.

fix: Do not allow setting of same property multiple times

---

lib/migration-steps/dispatch-proxy.js
test/unit/lib/migration-steps/migration-steps.spec.js

From #21, we currently didn't support Promises in the way we thought.
Thanks to @jody-zeitler for early adoption and finding this bug 🥇

Allow migration script to be async

---

lib/migration-payloads/index.js
lib/migration-payloads/validation/index.js
test/unit/lib/migration-payloads/validation/payload-validation-field-deletion.spec.js

Previously, we reported validation errors when a migration included deleting and then recreating a field. This was because deleted fields did not get removed from the internal state of the payload builder.
In addition, we no longer perform type change checks if we see that the parent step was a deletion.

fix(payloads): Do not report errors when fields are recreated

---

lib/migration-steps/validation.js
test/unit/lib/migration-steps/migration-steps-validation.spec.js

At https://github.com/contentful/migration-cli/pull/32 we partially fix the bug that rejects setting empty strings as content types descriptions. This PR allows also empty strings in steps validations.

fix(step/validations): allow empty strings as content type descriptions

---

.gitignore
.npmignore
package.json

In order to not distribute unnecessary stuff, we `.npmignore` a good chunk of stuff.
Note that `.DS_Store` and alike are ignored by default ([full list](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)).
It then wipes the `built` folder and triggers a rebuild - this is hooked to the `prepare` lifecycle, so that it gets executed after `npm install` and before `npm publish`.

Release pipeline

---

CONTRIBUTING.md

Update the `CONTRIBUTING` file to include a mention to Typescript. Maybe in the future we could also add some guidelines about or own expectations with regards to typing

docs(contributing): Mention typescript

---

test/end-to-end/assertions.js
test/end-to-end/content-transform.spec.js

Apparently it was not waiting/expecting finalizing the assertion, which lead to false passing test.

Fix test to validate server errors

---

src/bin/cli.ts
src/bin/lib/write-errors-to-log.ts
src/lib/action/entry-derive.ts
src/lib/action/entry-transform.ts
src/lib/interfaces/request.ts
test/unit/lib/actions/entry-transform.spec.ts
test/unit/lib/intent/entry-derive.spec.ts

When `undefined` is returned from the transform or derive function, we don't produce a value for that locale on the transformed/ derived entry. If the function returns `undefined` for all locales of an entry, in the case of transform, it doesn't get changed, and in the case of derive, no target entry is created and the source entry is left untouched. (This is documented already in the README)
Verbose comments on this one, I can reduce those if needed.

handle undefined returned values from transform and derive

---

package.json
src/bin/cli.ts
test/end-to-end/content-transform.spec.js
test/end-to-end/content-type.spec.js
test/end-to-end/derive-entry.spec.js
test/end-to-end/fields.spec.js
test/end-to-end/validations.spec.js
test/helpers/client.js
test/integration/migration.spec.js

Adds environment support to the CLI and uses them to run isolated tests.
Even if not being part of the closed beta, access to the explicit `master` environment should work just fine. Only creation and manipulation of environments is feature flagged.
**Note:**
This change may make it hard for people to contribute to our codebase, because tests use environments. That means that nobody can by default run any integration or e2e tests.
Combine that with the issue that travis won't run any of those tests for external contributors because of token security issues.
Ideally we can somehow fix the travis issue, so people at least could run the tests via a PR or push.

feat: make cli env aware

---

src/lib/fetcher.ts
test/unit/lib/fetcher.spec.ts

Fetch all entries to transform

---

examples/17-change-editor-interface-for-existing-content-type.js
src/lib/fetcher.ts
src/lib/offline-api/index.ts
test/integration/migration.spec.js

The version of the editor interface is increased server-side whenever it's parent content type gets published. We need to take that into consideration.
this PR fixes that.
Fixes #81

fix: Bump editorinterface's version

---

README.md
src/lib/intent/editorinterface-update.ts
src/lib/interfaces/content-type.ts

_When changing the editor interface of a field, I'd like to see those changes listed in the intents before approving the migration._
- Include field settings in editor interface intent
- Fix true/false label types
- Extend documentation for `changeEditorInterface`
> I'm not sure if this is the proper way of doing it — one thing that bothers me is that there's no spacing between the editor interface intent and the next intent. I couldn't figure out how to add it.
> Happy to be pointed in the right direction :)

Improvements to editor interface migrations

---

src/lib/offline-api/validator/schema/field-validations-schema.ts
test/unit/lib/offline-api/validation/payload-validation-field-validations.spec.ts

When a regexp validation is created through contentful ui, if no flag is
provided, it is set as `null`. After that, you are unable to update that
content model via migration-cli. This allows null values for that
validation property. Fixes #64 
I wasn't sure exactly where to put the test for this, but I think this was a reasonable place. Please advise if you prefer anything different.

Allow null values for flags in regexp validations

---

README.md
examples/usage-as-lib.js
src/bin/cli.ts
src/lib/migration-parser.ts
test/end-to-end/assertions.js
test/end-to-end/cli-as-lib.js
test/end-to-end/error-recovery.spec.js

When using the package as a library, it's a good idea to throw an error
instead of exiting with code 1. This way the user can recover from the
mistake somehow (e.g. deleting a throwaway environment on during continuous
integration).
This seems like it solves #111 too. 
- When using the `runMigration` export, make the function throw instead of process.exit(1).
- When using the `default` export, proceed as before by running process.exit(1) on errors. 
I'm making continuous integration scripts that creates and deletes throwaway branches on CircleCI to test that the migration scripts are valid before they are merged. When the migration fails, I would like it to delete the newly created branch. This is currently impossible because this library will `process.exit(1)` for me. 
Actual …

feat: Add support for throwing instead of process.exit(1) on errors

---

src/bin/cli.ts

The run function swallows errors right now in a try catch block. When
used as a library with shouldThrow = true, this function should
rethrow the error so that the parent function knows that the process
was unsuccessful.
Add a simple `if (shouldThrow) throw err` at the bottom of the run
function.
Our CI passes but the migration fails.

fix runMigration as lib should throw instead of swallowing errors

---

package.json

[string.js](https://github.com/jprichardson/string.js/issues/212) which is a dependency of [nixt](https://github.com/vesln/nixt/pull/18) is vulnerable.
This PR fixes that.
Even though the vulnerable code is not used it's good to remove it.

Fix vulnrerable dependency

---

examples/15-derive-entry-n-to-1.js
examples/19-derive-entry-n-to-n.js
examples/20-derive-entry-n-to-n.js
src/lib/action/entry-derive.ts
test/unit/lib/actions/entry-derive.spec.js

fixes #127 
When the reference field for a deriveEntry migration is an array of linked entries, the derived entry now becomes the first item in an array. (Previously, the derived entry was linked as a single entry, ignoring the type of the reference field). Also add a new example showing this behavior.

feat(deriveEntry): n to n

---

src/lib/action/entry-derive.ts
src/lib/entities/entry.ts
src/lib/utils/is-defined.ts
test/unit/lib/actions/entry-derive.spec.js

Fixes https://github.com/contentful/contentful-migration/issues/156
The problem is that we always defaulted it back to `true` when any falsy value was passed.
I also removed use of `util/isNullOrUndefined` because it is deprecated since Node 4.

Respect shouldPublish flag when set to false

---

src/lib/fetcher.ts
test/fixtures/contentful-migration-integration.js
test/unit/lib/content-types-in-chunks.spec.ts
test/unit/lib/fetcher.spec.ts
test/unit/lib/migration-parser.spec.ts

Fixes https://github.com/contentful/contentful-migration/issues/157
Previously we did not iterate over all the pages in the API, leading to some locales being left out.
Now entries, content types and locales are all fetched until all pages have been exhausted.

fix: fetch all locales from API

---

.travis.yml
package.json
test/unit/bin/lib/config.spec.ts
test/unit/lib/actions/entry-transform.spec.ts
test/unit/lib/content-types-in-chunks.spec.ts
test/unit/lib/deleted-ct-entries.spec.ts
test/unit/lib/fetcher.spec.ts
test/unit/lib/intent-list/intent-list.spec.ts
test/unit/lib/intent-validator/updates.spec.ts
test/unit/lib/intent-validator/validate-steps.ts
test/unit/lib/intent/composed-intent.spec.ts
test/unit/lib/intent/editorinterface-copy.spec.ts
test/unit/lib/intent/editorinterface-reset.spec.ts
test/unit/lib/intent/editorinterface-update.spec.ts
test/unit/lib/migration-chunks/validation/validate-chunks.ts
test/unit/lib/offline-api/build-payloads.ts
test/unit/lib/offline-api/validation/validate-batches.ts
tsconfig-dev.json

Previously we were skipping the tests when linting typescript files.  
Now we always build and lint the test folders as well during the CI test run.

Enable linting for tests

---

index.d.ts

Before, TypeScript projects using the `strict` compiler settings were unable to compile when `contentful-migration` was imported. The following error was displayed
error TS7010: 'toTheTop', which lacks return-type annotation, implicitly has an 'any' return type.

Make typings compatible with strict typescript

---

src/lib/intent-validator/content-transform.ts
src/lib/intent-validator/schema-validator.ts
test/unit/lib/intent-validator/content-transform.spec.ts

shouldPublish should accept 'preserve' in addition to boolean values
Add 'preserve' as a valid option to validations for shouldPublish field
https://github.com/contentful/contentful-migration/pull/143#issuecomment-451451263

fix ContentTransformIntentValidator

---

src/lib/entities/content-type.ts
src/lib/interfaces/content-type.ts
test/unit/lib/offline-api/build-payloads.ts

Fixes https://github.com/contentful/contentful-migration/issues/173
`editorInterface` payload can have custom sidebar configuration saved. Currently all related methods just override `sidebar` configuration. This PR fixes the behavior, so if `sidebar` configuration isn't overwritten if present in the initial payload.

fix: editorInterface methods do not reset custom sidebar anymore

---

index.d.ts
src/bin/lib/config.ts
src/bin/lib/contentful-client/index.ts
src/bin/lib/contentful-client/proxy.ts
test/unit/bin/lib/config.spec.ts

This fixes a bug that caused unauthenticated proxies to fail (if the proxy doesn't require a user/pw). 
We released it as beta to confirm it fixes the user issue (since enterprise proxies are unique and challenging to debug). It did, so let's get this into the regular release of contentful-migration.

fix(proxy): allow proxy options in argv 

---

README.md

Fix "Usage as a library" example error logging
Now pass the error object to `console.error`
That example was wrong, so I'm fixing it.

chore: "Usage as a library" example error logging

---

src/lib/entities/content-type.ts
src/lib/interfaces/content-type.ts
test/unit/lib/offline-api/build-payloads.ts

Fix for a new custom editor extensions feature.
Change in editorInterface implementation so migrations don't override `editor` property if it was set already.

editorInterface methods do not reset custom editor extension

---

examples/09-validate-validations.js
src/lib/offline-api/validator/schema/field-validations-schema.ts
test/end-to-end/validations.spec.js
test/fixtures/contentful-migration-integration.js
test/integration/migration.spec.js

addresses https://github.com/contentful/contentful-cli/issues/145

fix(validations): add prohibitRegexp validation

---

README.md
examples/16-change-field-control.js
examples/17-change-field-control-for-existing-content-type.js
examples/18-change-field-control-for-existing-content-type-adding-help-text.js
examples/21-copy-field-control.js
index.d.ts
src/lib/migration-steps/index.ts
test/unit/lib/migration-steps/migration-steps.spec.js

Fixes inconsistency in changeFieldControl signature raised in issue #198
Same as for the sidebar methods, widgetNamespace should always be mandatory and always precede widgetId. This is due to the fact that widgetId is only unique in said namespace.

Consistent signature of changeFieldControl() in README, index.d.ts and index.ts

---

src/lib/offline-api/index.ts

We have an erorr message `cannot save CT sldihfsd because it does not exist` which might be confusion a tiny bit for folks who does not know what CT stands for.

fix(offline-api): Change CT to content type in the error message

---

src/bin/cli.ts

Changes `runMigration` to throw when a migration file is missing or is invalid.
When a migration file is missing or invalid, the script exits without indicating an error which can be caught programmatically. It's impossible to see the error state when using `runMigration` as a library, even though the possibility to indicate this by throwing is present.
This PR changes this behavior so the function throws in this cases.
The code calling `runMigration` will treat a migration as successfully even if the migration script is missing or invalid.

fix: throw on missing or invalid file

---

.travis.yml
index.d.ts
package-lock.json
package.json

We correctly import `axios` in the type definitions `index.d.ts`.
To ensure that typings are checked on CI we run `npm run test-typescript-declaration`. This requires us to upgrade typescript to the latest version.

fix(typing): 'axios' import in typings

---

package-lock.json
package.json

Updated `https-proxy-agent` dependency due to [vulnerability](https://www.npmjs.com/advisories/1184).

fix(dependency): Update https-proxy-agent dependency

---

README.md

Updates the README to include the web-app description of a field to the corresponding content model field
This adds the phrase "Entry title" to the description for the `displayName` option on the Content Model documentation, since that is what a web-app user might know the field as
Just an instance where the wording differs between the web app and the under-the-hood schema. I think adding this kind of clarification can help bridge the knowledge gap for anyone used to using the web app GUI

docs(README): Update README to include "Entry title" phrase

---

src/bin/cli.ts

Logs any errors that are thrown when requiring migration scripts.
Previously when a migration contained syntax errors or could not be `require`d, users would only get a generic message:
>The migrations/cm001-create-seo-fields.js script could not be parsed, as it seems to contain syntax errors.
This is not very helpful because it does not describe the underlying issue.

fix: log errors when requiring migration scripts

---

src/lib/offline-api/validator/schema/field-validations-schema.ts
test/unit/lib/offline-api/validation/payload-validation-field-validations.spec.ts

Fixes "nodes" validation for RichText adding support for all blocks and inlines.
added "nodes" validation for 
```
'embedded-asset-inline'
'asset-hyperlink'
'hyperlink'
```
Using the migration tool fails to properly migrate since it doesn't allow the use of 
```
'embedded-asset-inline'
'asset-hyperlink'
'hyperlink'
```

Allow "nodes" validation for all blocks and inlines

---

.circleci/config.yml
package-lock.json
package.json

Sadly our setup is somewhat broken and constantly generates wrong coverage numbers.
Those result in red checks, causing auto merges to fail.
Remove the coverage - which was unreliable anyway - and unblock automatic merging.

chore: remove code coverage checks

---

src/lib/offline-api/validator/schema/field-validations-schema.ts
test/unit/lib/offline-api/validation/payload-validation-field-validations.spec.ts

embedded-asset-inline doesn't exists and should be embedded-asset-block instead
migration fails when using "embedded-asset-inline" in validation

validation should be asset-block instead of asset-inline

---

index.d.ts

Adding TypeScript definition for `configureEntryEditor`.
Added the `configureEntryEditor` definition within the `ContentType`'s definition

Added configureEntryEditor definition

---

index.d.ts

This adds the missing `yes` param to the migration config in the definitions file so that confirmation can be skipped when calling `runMigration` in typescript.
Noticed that this was missing while working on a project which is using the contentful migration tool via typescript in an automated context; we added `// @ts-ignore` as a workaround, but it would be nice to have it fixed properly.

fix: add missing `yes` param to migration config

---

src/lib/action/action.ts
src/lib/intent-list/index.ts
src/lib/migration-chunks/validation/tag.ts
src/lib/offline-api/index.ts
src/lib/offline-api/validator/entry.ts
src/lib/offline-api/validator/errors.ts
src/lib/offline-api/validator/tags-on-entry.ts
test/unit/lib/offline-api/validation/payload-validation-non-existing-tags.spec.ts
test/unit/lib/offline-api/validation/validate-batches.ts

Add validation to not allow attaching non-existing tags to entries.
We don't yet check for duplicate tags (which would be done via a joi schema check), because of scope and a bug in the joi version we are using.

feat(tags): validation

---

src/lib/action/entry-transform-to-type.ts
src/lib/action/entry-transform.ts
src/lib/utils/should-publish-local-changes.ts
test/unit/lib/actions/entry-transform-to-type.spec.ts
test/unit/lib/actions/entry-transform.spec.ts
test/unit/lib/utils/should-publish-local-changes.spec.ts

In case of a published entry but with unpublished changes, `shouldPublish: 'preserve'` would always resolve in a published entry. With these changes we check for pending changes and only publish if there are none.
Resolves #229, #223

fix(publish): respect entry state CHANGED for preserve value

---

src/bin/cli.ts
test/helpers/client.js

Fix for: [request with double slashes](https://github.com/contentful/contentful-migration/issues/515)
Wrong request url example 
`https://api.contentful.com/spaces/SPACE_ID/environments/master//content-types`
Solution:
replace _Array.join()_ for _path.join()_ in makeRequest()

FIX request url with double slashes

---

README.md
src/lib/action/entryeditor-configure.ts
src/lib/action/entryeditor.ts
src/lib/action/entryeditors-configure.ts
src/lib/entities/content-type.ts
src/lib/intent/entryeditors-configure.ts
src/lib/intent/index.ts
src/lib/interfaces/content-type.ts
src/lib/interfaces/raw-step.ts
src/lib/migration-steps/action-creators.ts
src/lib/migration-steps/index.ts
test/unit/lib/entities/editor-interface.spec.ts

Adding support for migrating [multiple editors in editor_interface](https://www.contentful.com/developers/docs/concepts/editor-interfaces/#custom-editor)
Adds a new method `configureEntryEditors`
Could have rewritten the previous method `configureEntryEditor` but this would break any previous scripts relying on its intended behaviour.

feat(EntryEditors): Add support for migrating entry editors [EXT-2359]

---

src/lib/action/entry-transform.ts
test/unit/lib/actions/entry-transform.spec.ts
test/unit/lib/migration-parser.spec.ts

Fixes: https://github.com/contentful/contentful-migration/issues/329
transformEntries DSL was publishing all entries by default, now it will be 'preserve' by default

fix(transformEntries): shouldPublish will 'preserve' by default

---

README.md

Fix the `transformEntryForLocale(fields, locale)` docs: confusion betwen `from` -> `fields`
`from` is an array.
`fields` is the object we are describing.

Fix `transformEntries` doc in readme

---

README.md
src/bin/lib/config.ts
src/bin/usage-params.ts
test/integration/bin/lib/contentful-client.spec.js
test/unit/bin/lib/config.spec.ts

Added support for passing `headers` option down to `contentful-management`. I also added `-H/--header` option to the CLI.
A similar option/flag will be added to other related libraries as well (e.g. contentful/contentful-export#562).
To enable users to pass custom HTTP headers. This is especially useful when trying out alpha features.

feat: add custom headers support

---

.circleci/config.yml

Bump node image version to fix semantic release failing.

ci: bump node from 12 to 14

---

examples/32-create-fields-with-initial-values.js
examples/32-initial-values.js
src/lib/intent-validator/field-update.ts
src/lib/offline-api/index.ts
src/lib/offline-api/validator/content-type.ts
src/lib/offline-api/validator/display-field.ts
src/lib/offline-api/validator/errors.ts
src/lib/offline-api/validator/field-deletion.ts
src/lib/offline-api/validator/schema/fields-schema.ts
src/lib/offline-api/validator/schema/index.ts
src/lib/offline-api/validator/schema/schema-validation.ts
src/lib/offline-api/validator/type-change.ts
test/unit/lib/offline-api/validation/payload-validation-field-initialvalue.spec.ts
test/unit/lib/offline-api/validation/validate-batches.ts

Allow defining `initialValue` property on content type fields. Validate for supported field types, existing locales and correct type of initial values.

feat: support initial values

---

examples/32-create-fields-with-initial-values.js
src/lib/offline-api/validator/errors.ts
src/lib/offline-api/validator/schema/fields-schema.ts
src/lib/offline-api/validator/schema/schema-validation.ts
test/unit/lib/offline-api/validation/payload-validation-field-initialvalue.spec.ts

Update validations to allow defining `initialValue` for short text list fields. Extend tests and examples.

feat: support initialValue for array of symbols

---

.gitignore
README.md
index.d.ts
src/lib/action/entry-derive.ts
src/lib/intent-validator/entry-derive.ts
src/lib/interfaces/entry-derive.ts
test/unit/lib/actions/entry-derive.spec.js
test/unit/lib/intent-validator/entry-derive.spec.ts

Add `preserve` to `shouldPublish` option of `deriveLinkedEntries`
`shouldPublish` now accepts the string `preserve`. When you set `preserve` will keep current states of the source entries.
When you want to derive linked entries usually is needed to preserve the original state of the source, otherwise the tool will publish draft entries (so items not yet approved) or un-publish already published entries.
This solves the feature request #691 

feat: Add 'preserve' to 'shouldPublish' option of 'deriveLinkedEntries'

---

src/lib/offline-api/validator/schema/field-validations-schema.ts
test/unit/lib/offline-api/validation/payload-validation-field-validations.spec.ts

Adds `table` validation for Rich Text node types.
When generating a migration using `contentful space generate migration` or by copying the validations form the JSON export/preview of a Rich Text field, these now include `table` as a node type.
By adding these node type, those imports are no longer failing.

Adds `table` to Rich Text node types

---

README.md
examples/specify-migration-function.js
index.d.ts
src/bin/cli.ts

This Pull Request enhances the experience of using `contentful-migration` as a library, by allowing the migration function to be specified as a configuration option, rather than in a separate file.
This Pull Request:
- Adds a new configuration option `migrationFunction`, which accepts a function of type `MigrationFunction`
- Updates the expected type of the `RunMigrationConfig` to expect *either* the `filePath` *or* the `migrationFunction`
- If specified, the supplied migration function is used instead of importing the function from a file
- Documents the new configuration option
- Adds an example script to the `/examples` folder
Please note that I've changed the exported `RunMigrationConfig` from an `interface` to a `type`.
As it stands, `contentful-migration` is available for use as a …

Allow the migration function to be supplied directly

---

examples/32-create-fields-with-default-values.js
index.d.ts
package-lock.json
package.json
src/lib/intent-validator/field-update.ts
src/lib/interfaces/content-type.ts
src/lib/offline-api/validator/errors.ts
src/lib/offline-api/validator/schema/fields-schema.ts
src/lib/offline-api/validator/schema/schema-validation.ts
test/unit/lib/offline-api/validation/payload-validation-field-defaultvalue.spec.ts

Rename `initialValue` for content type fields `defaultValue`.
The feature was renamed so we’re renaming the property as well.

fix: rename initial value default value

---

README.md
examples/32-create-public-tag.js
index.d.ts
src/lib/action/tag-create.ts
src/lib/entities/tag.ts
src/lib/intent/tag-create.ts
src/lib/interfaces/api-tag.ts
src/lib/interfaces/raw-step.ts
src/lib/migration-steps/action-creators.ts
src/lib/migration-steps/index.ts
src/lib/offline-api/index.ts
test/integration/migration.spec.js
test/unit/lib/intent/composed-intent.spec.ts
test/unit/lib/migration-chunks/validation/tag.spec.js
test/unit/lib/migration-steps/migration-steps.spec.js

Introduce Tag `visibility` for `createTag`
In your migration script, you will be able to get a tag's visibility by calling the getter `visibility`. 
If not explicitly set a tag's visibility will be `private`.

feat(tags): support for public tags

---

src/bin/usage-params.ts

Add typeguard to fix typescript error which is triggered on test runs:
```
src/bin/usage-params.ts:11:50 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
Type 'number' is not assignable to type 'string'.
11     const filePath = path.resolve(process.cwd(), args._[0])
~~~~~~~~~
```

chore(types): add type guard

---

README.md

Add the `'app'` option to the possible widget namespaces of `changeFieldControl`.
As you can see [here](https://github.com/contentful/contentful-migration/blob/e7a2f95c0cb225e92ecfb19a50e7dcf8de8f172e/index.d.ts#L186), `changeFieldControl` supports `'app'` as a possible value of the `widgetNamespace` param.
So this PR documents that.

docs: Add "app" to changeFieldControl's widget namespaces

---

examples/34-create-with-link-to-non-existing-content-type.js
test/integration/migration.spec.js

Add test coverage to document current behavior on how validation for linking Content Types works.
Current behavior: Content Types with link fields which reference non-existing entities can still be created via the migration tool. Ideally, this should be fixed in the future to only allow linking to existing content types.

chore(linkContentType): add test to document current link validation

---

package-lock.json
package.json

This PR is fixing the issue `Cannot find module 'uuid'` that occurs when you try to install and use the latest version `v4.6.0`
closes #984

fix(config): Fix missing uuid dependency

---

README.md
docs/validation.md
index.d.ts
src/lib/intent/base-intent.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-control.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-id.ts
src/lib/intent/editor-layout/editor-layout-create-field-group.ts
src/lib/intent/editor-layout/editor-layout-delete-field-group.ts
src/lib/intent/editor-layout/editor-layout-delete.ts
src/lib/intent/editor-layout/editor-layout-move-field.ts
src/lib/intent/editor-layout/editor-layout-update-field-group.ts
src/lib/interfaces/intent.ts
src/lib/offline-api/index.ts
src/lib/offline-api/validator/editor-interface.ts
src/lib/offline-api/validator/errors.ts
src/lib/offline-api/validator/field-groups-count.ts
src/lib/offline-api/validator/schema/editor-layout-schema.ts
src/lib/offline-api/validator/schema/schema-validation.ts
src/lib/utils/editor-layout.ts
test/unit/lib/migration-chunks/validation/editor-layout.spec.js

Cover more validation errors for the editor layout:
- too many tabs
- too many field sets
- too few field groups
- tab with a field set control
- field set with a tab control
Plus fix the readme and how editor interface intents are grouped

feat: validate editor layout [DANTE-407]

---

examples/xx-delete-editor-layout-field-set.js
examples/xx-delete-editor-layout-tab.js
examples/xx-move-field-in-existing-editor-layout.js
src/lib/intent/base-intent.ts
src/lib/intent/composed-intent.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-control.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-id.ts
src/lib/intent/editor-layout/editor-layout-create-field-group.ts
src/lib/intent/editor-layout/editor-layout-create.ts
src/lib/intent/editor-layout/editor-layout-delete-field-group.ts
src/lib/intent/editor-layout/editor-layout-delete.ts
src/lib/intent/editor-layout/editor-layout-move-field.ts
src/lib/intent/editor-layout/editor-layout-update-field-group.ts
src/lib/interfaces/intent.ts
src/lib/migration-chunks/validation/editor-layout.ts
src/lib/migration-chunks/validation/errors.ts
test/end-to-end/assertions.js
test/end-to-end/editor-layout.spec.js
test/integration/migration.spec.js
test/unit/lib/migration-chunks/validation/editor-layout.spec.js

Update field grouping migration.
* Add E2E tests
* Unify and group field grouping plan messages
* Fix: fetch content type when moving fields for field ID validation
* Fix: allow deleting a newly created field group
* Fix: throw error when attempting to create an editor layout if it already exists
We added the field grouping migration in multiple steps. Instead of creating overhead by iterating on the output several times this PR aligns the output and adds matching E2E tests after finishing the functionality.

feat: align output and add E2E tests for field grouping

---

src/lib/intent/base-intent.ts
src/lib/intent/composed-intent.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-control.ts
src/lib/intent/editor-layout/editor-layout-change-field-group-id.ts
src/lib/intent/editor-layout/editor-layout-update-field-group.ts
src/lib/interfaces/intent.ts
src/lib/migration-chunks/validation/editor-layout.ts
src/lib/migration-chunks/validation/errors.ts
test/unit/lib/migration-chunks/validation/editor-layout.spec.js

Add more validations for field group IDs and names to field grouping migration.
* Validate field group ID format when creating field group or changing field group ID
* Validate field group name length when updating field group
* Check if field group exists when changing group controls
* Update field group IDs used for validation when changing field group ID

feat: add more field group ID / name validation

---

package-lock.json
package.json

Contentful-management couldn't be bumped automatically due to an outdated ts version (https://github.com/contentful/contentful-migration/pull/1018), therefore we are bumping both together here.

fix(dependencies): bump ts + contentful-management

---

index.d.ts
package-lock.json
src/lib/entities/content-type.ts
src/lib/interfaces/content-type.ts
src/lib/migration-chunks/validation/index.ts
test/end-to-end/assertions.js
test/integration/migration.spec.js
test/unit/lib/entities/editor-interface.spec.ts

Bring [editor-layout-draft](https://github.com/contentful/contentful-migration/tree/editor-layout-draft) up to date with the master branch.

Merge master into editor-layout-draft branch

---

src/lib/migration-steps/action-creators.ts

Make an optional chain for calling methods on `callsite` object.
On the AWS Lambda execution environament `callsites` library just return empty object, so calling `getFileName()` or `getLineNumber()` is throwing errors.
PR addresses that issue by using the `?` operator before the method call. If the object is empty, then it won't fail. 
Addresses [#1111](https://github.com/contentful/contentful-migration/issues/1111)

Make optional chain for calling methods on callsite object

---

tsconfig-dev.json
tsconfig.json

Add the `"declaration": true` flag to tsconfig.json and tsconfig-dev.json.
This flag instructs the typescript compiler to output .d.ts files alongside the javascript in `built`. These can be used by typescript projects that consume contentful-migration as a dependency.
I'm working on updates to deluan/contentful-migrate right now, and am
finding that I need to recreate a lot of type information that already
exists in this library. In addition to being a lot of work, duplicating
that information makes my work fragile. It can easily become out of sync
when the types inside contentful-migration change.
If you add this flag, the type declarations (.d.ts files) will become
part of the npm package, letting me depend on them without rewriting
them by hand.
In #213, @chrislambe comments:
> It …

Export type declarations to support use as library

---

examples/46-can-set-display-field-before-annotations.js
src/lib/intent/base-intent.ts
src/lib/intent/content-type-annotate.ts
src/lib/intent/content-type-update.ts
src/lib/intent/field-create.ts
src/lib/intent/field-move.ts
src/lib/intent/field-update.ts
test/integration/migration.spec.js

This is to fix a bug a customer reported when using `setAnnotations`. Depending on the order in which you manipulate a content type in your migration script, the migration would either throw a validation error when interacting with the API or work as expected. 
The following worked well:
```js
module.exports = function(migration) {
const annotatedContentType = migration
.createContentType('annotatedWithDisplayField')
.name('Blog Post')
.setAnnotations(['Contentful:AggregateRoot'])
.displayField('name')
annotatedContentType
.createField('name')
.name('name')
.type('Symbol')
.localized(false)
.required(true)
.validations([{ unique: true }])
.disabled(false)
.omitted(false)
}
```
Whereas this did not and would throw a 422:
```js
module.exports = function(migration) {
const …
```

fix(annotations): group annotate intents with ct and field updates

---

index.d.ts
src/bin/lib/config.ts
src/lib/fetcher.ts

The `requestBatchSize` was not being exposed in all interfaces. Thereore users trying to use `runMigration' would not see it proposed as an option. This PR exposes the param and cleans up types a bit.

fix(types): change types to expose requestBatchSize []

---

src/bin/lib/config.ts
test/unit/bin/lib/config.spec.ts

Picks up the initiative from https://github.com/contentful/contentful-migration/pull/1096 and the related issue https://github.com/contentful/contentful-migration/issues/1095.
Use `managementToken` as fallback if no `cmaToken` is provided in `.contentfulrc`. We want to keep the `cmaToken` to ensure backwards compatibility, but allow for `managementToken` as well as it is the new default in `contentful-cli`.

fix: use management token as fallback

---

README.md
src/lib/action/entry-derive.ts
src/lib/action/entry-transform-to-type.ts
src/lib/action/entry-transform.ts
test/unit/lib/actions/entry-derive.spec.js
test/unit/lib/actions/entry-transform-to-type.spec.ts
test/unit/lib/actions/entry-transform.spec.ts

Provide the entry id for several transform callbacks.
For all transformation functions (`transformEntries`, `deriveLinkedEntries` and `transformEntriesToType`) we provide the entry id of the entry in scope in the call signature of the transform callbacks. This allows for cross checking the id with any other source, or more custom validations within scope.
We opted-in for an wrapping object as a third parameter to eventually enrich the callback with further data in the future.
**Example:** (more in the updated readme)
```js
module.exports = function (migration) {
migration.transformEntries({
contentType: 'newsArticle',
from: ['author', 'authorCity'],
to: ['byline'],
transformEntryForLocale: function (fromFields, currentLocale, {id}) {
if(id === '<specific-entry-id>') {
return;
}
if …
```

feat: provide entry id for transform and derive functions

---

index.d.ts

Add missing type in `transformEntryForLocale` function
This pr https://github.com/contentful/contentful-migration/pull/1212 was merged and released but it missed to add the types in index.d.ts file, this gives following typescript error in client code.
```
Type '(from: any, currentLocale: any, { id: entryId }: { id: any; }) => Promise<any>' is not assignable to type '(fromFields: ContentFields, currentLocale: string) => any'.
Target signature provides too few arguments. Expected 3 or more, but got 2.ts(2322)
```

fix: Add missing typing

---

src/lib/offline-api/validator/schema/field-validations-schema.ts

Allow `null` value for validation `message`
It turns out the `message` value for validations can be set to `null`. This PR updates the Ajv schema to reflect this.
The Ajv schema is not correct for the possible `null` value for `message`

fix: allow null type for validation message

---

index.d.ts
src/bin/lib/config.ts
test/teardown.js
test/unit/bin/lib/config.spec.ts

Support `host` as a provided option (in addition to contentfulrc.json)

feat(): support host option

---

README.md

* Fixed values for `linkType`
* Wrapped referenced types in backticks
* Fixed minor typo in documentation
In my experience with Contentful migration scripts, `linkType` does not share values with `Type` as the documentation states, but rather takes in a `string` value of either `"Asset"` or `"Entry"`.
I have wrapped referenced types in backticks to be consistent with how they are referenced earlier in the documentation.
I am using Contentful and was reading through the documentation when I found these typos and changes.

fix(docs): Fix `linkType` values & typos

---

src/bin/cli.ts

Safe logging of batched erors
We assume that the errors received are all of type `BatchedError`. This is not the case. To handle this situation gracefully, we have to add checks for the shape of received errors. 
Reported by a customer.
fixes https://github.com/contentful/contentful-migration/issues/1257

fix: logging batch errors

---

package-lock.json
package.json

See: https://github.com/contentful/contentful-migration/issues/1267
Upgrade axios to latest available version
Using contentful-migration introduces a vulnerable transitive dependency into any user that uses this library. This fix will mitigate this.

Update axios to 1.6.2 to remove vulnerabilities

---

src/bin/cli.ts

Fix the URL passed to Axios by makeRequest
When you use the makeRequest function in a JS migration script, I encountered a URL not found error because the current makeBaseUrl function does not prepend the protocol and domain to the URL.
I'm trying to set up a CI/CD pipeline for a Contentful project. I need the makeRequest function for a migration.

Bug fix for makeRequest base URL logic

---

src/bin/cli.ts

Allow users to override the default API host to migrate EU spaces

feat: allow overriding the default API host

---

examples/22-create-rich-text-field-with-validation.js
test/integration/migration.spec.js

Added missing marks and nodeTypes to example 22 to improve it as a reference
Example 22 (create-rich-text-field-with-validation) expanded to include marks such as "bold", and missing node-types such as "table".
I created a new rich text field with everything enabled, then used the contentful cli tool to generate a migration based on that; the output of which I used to fill in the blank spots of the example code.
To improve the example as a reference. I recently had a teammate struggle to find examples of adding table support to rich text using this library—looking at this example I found that it was missing just a few items to serve as a complete reference.

rich text example: enabledMarks & enabledNodeTypes

---

examples/54-create-experience-type.js
src/lib/interfaces/annotation.ts
src/lib/offline-api/index.ts
test/end-to-end/assertions.js
test/end-to-end/content-type.spec.js
test/integration/migration.spec.js

Add support for annotations used by experience types in the validations of the offline API.
[TDD] To ensure it is working through this change, this PR includes an example migration, an integration test, and an e2e test which actually tests this local validation layer.
To test the following things locally, check out the CONTRIBUTION.md and add the necessary env variables:
- `CONTENTFUL_SPACE_ID` (space name must be "contentful-migration')
- `CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN` (for e2e & integration test)
- `CONTENTFUL_MANAGEMENT_ACCESS_TOKEN` (same as above but other name, used for manual migration run)
1. Run e2e test locally: `npm run build && npm run test:e2e`
2. Run integration test locally: `npm run build && npm run test:integration`
3. Run example migration locally: `node …

feat: support annotation for experience types [SPA-2047]

---

src/bin/lib/steps-errors.ts

Makes sure to check for a file url instead of a file path before providing it to `readFileSync`
Fixes issue #1332

fix: fixes `no such file or directory` when migration fails

---

src/lib/offline-api/validator/schema/field-validations-schema.ts
src/lib/utils/resource-links.ts
test/unit/lib/offline-api/validation/payload-validation-resource-links.spec.ts
test/unit/lib/offline-api/validation/payload-validation-rich-text-resource-link-embeds.spec.ts

This bumps the limit to be in sync with the one enforced through the API.

feat: bump limit of allowed sources

---

index.d.ts

Allow adding external resources to allowed resources in the content type to enable [Native External References](https://www.contentful.com/help/orchestration/native-external-references/).
I didn’t update the tests for this as the change is tiny and the test would have required an app to be installed making it much more complicated than the change.

feat: allow external resources to be set

---

index.d.ts

As mentioned in issue #1221, the type definition for `configureEntryEditors` is missing.
I also added `editor-builtin` as an option for `widgetNamespace` for these entry editors. I'm not entirely sure if `builtin` is still a possible choice for these, given that it does seem to require `editor-builtin`, but I've left the choice there.

feat(types): add configureEntryEditors definition

---

package-lock.json
package.json

Explicitly upgrade axios to ^1.7.9 so downstream consumers know that the latest is the acceptable valid version.
Even though axios was previously bumped to 1.7.9 in the lockfile, 1.7.4 was still marked as valid for downstream consumers, so they wouldn't get the new version without regenerating their lockfile or executing npm audit fix in their projects that use contentful-migration.

fix: explicitly upgrade axios to 1.7.9 [ZEND-5779]

---

package-lock.json
package.json

Explicitly upgrade contentful-management to ^11.40.3 so downstream consumers know that the latest is the acceptable valid version.
Even though contentful-management was previously bumped to 11.40.3 in the lockfile, 11.35.1 was still marked as valid for downstream consumers, so they wouldn't get the new version without regenerating their lockfile or executing `npm audit fix` in their projects that use contentful-migration.

fix: explicitly upgrade contentful-management to ^11.40.3 [ZEND-5779]

---

src/lib/offline-api/validator/schema/allowed-resources-schema.ts
test/unit/lib/offline-api/validation/payload-validation-resource-links.spec.ts
test/unit/lib/offline-api/validation/payload-validation-rich-text-resource-link-embeds.spec.ts

Allows custom `type` parameter in `allowedResources` to support NER
If the `type` starts with `Contentful:` we validate whether it is an allowed (internal) ResourceType and whether the additional properties are correct. If it is a custom `type` which is used by NER no additional properties are allowed.

feat: allow NER resource types in allowedResources

---

index.d.ts

Currently its pretty easy to mistype or put the wrong `widgetId` when changing editor interfaces. This PR introduces function overloading to the `index.d.ts` file to restrict this from `string` to the widget IDs listed in your website:
https://www.contentful.com/developers/docs/extensibility/app-framework/editor-interfaces/.
I'm sick of guessing the wrong `widgetId` and would prefer a nicer developer experience. Copying these changes locally into our production application very clearly shows when there is an invalid `widgetId` for a builtin widget. Examples:
This catches these errors before they happen (`number` is not a valid widgetId)

Improve types for builtin editor widget IDs

---

README.md
examples/16-typescript-migration.ts
examples/55-transform-content-with-locale-based-publishing.js
examples/55-transform-content-with-locale-based-publishing.ts
index.d.ts
package-lock.json
package.json
src/lib/action/entry-derive.ts
src/lib/action/entry-transform.ts
src/lib/entities/entry.ts
src/lib/intent-validator/content-transform.ts
src/lib/intent-validator/entry-derive.ts
src/lib/intent-validator/entry-transform-to-type.ts
src/lib/intent/entry-transform.ts
src/lib/interfaces/api-entry.ts
src/lib/interfaces/content-transform.ts
src/lib/interfaces/entry-derive.ts
src/lib/interfaces/entry-transform-to-type.ts
src/lib/interfaces/request.ts
src/lib/offline-api/index.ts
src/lib/utils/should-publish-local-changes.ts
test/helpers/make-api-entry.ts
test/unit/lib/intent/entry-derive.spec.ts
test/unit/lib/utils/should-publish-local-changes.spec.ts
tslint.json

Support for using locale-based publishing is added to keep the status more granular.
https://github.com/user-attachments/assets/5b6c5e74-cd71-4c33-8248-0f69bf982346

feat: add support for locale based publishing [TOL-2810]

---

index.d.ts

fixes https://github.com/contentful/contentful-migration/issues/1466, introduced in https://github.com/contentful/contentful-migration/pull/1462

fix: changeFieldControl settings are optional []

---

src/lib/offline-api/validator/schema/allowed-resources-schema.ts
test/unit/lib/offline-api/validation/payload-validation-resource-links.spec.ts

Regex validation for `allowedResources` for NER did not match the regex for [ResourceProvider](https://github.com/contentful/extensibility-api/blob/main/lib/entities/resource-provider/schema.ts#L28) and [ResourceType](https://github.com/contentful/extensibility-api/blob/main/lib/entities/resource-type/validator.ts#L31C72-L31C84) in the extensibility-api

Fix allowedResources regex validation []

---

src/lib/offline-api/validator/schema/content-type-schema.ts
test/unit/lib/offline-api/validation/payload-validation.spec.ts

Increases _maximum possible fields allowed_ from 50 to 100.
Change `content-type-schema` variable.

fix: increase content type max fields to 100 [ZEND-6191]

---

package-lock.json
package.json

This reverts commit 1a1d261e4cc913c5a520165beddccd05c6835f6b.
semantic-release v23 >= requires a higher version of node than `contentful-migration` supports, so revert upgrade back to supported version.

Revert "build(deps-dev): bump semantic-release from 21.1.2 to 24.1.0 [ZEND-6396]

---

.github/dependabot.yml
package-lock.json
package.json

Downgrading semantic-release since the latest is not compatible with node v18. Updating our dependabot config to ignore any major version updates for semantic-release.
Also fixing the dependabot timezone value to a valid value.

chore: downgrade and ignore semantic-release [DX-236]

---

README.md

My recent PR https://github.com/contentful/contentful-migration/pull/1529  introduced `useLocaleBasedPublishing` prop documentation within the `transformEntryForLocale` description. Sorry! 🙏

docs: correction in transformEntriesToType config

---

package-lock.json
package.json

Bump axios to 1.12.2 to address security concern.
Addresses concern first notified in contentful.js that also uses axios: https://github.com/contentful/contentful.js/issues/2567
-   [ ] Implemented feature

fix: bump axios to 1.12.2 [DX-429]
